"""make user_id nullable and add ip_address

Revision ID: 1a555ce05e87
Revises: f6ea3703747f
Create Date: 2026-07-05 15:11:15.759467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a555ce05e87'
down_revision: Union[str, Sequence[str], None] = 'f6ea3703747f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('ip_address', sa.String(), nullable=True))
    op.alter_column('analyses', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analyses', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('analyses', 'ip_address')
    # ### end Alembic commands ###
