"""remove consent_photo_storage from users

Revision ID: 616f5d550c0c
Revises: cfc3f6f2935e
Create Date: 2026-07-09 13:25:28.145031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '616f5d550c0c'
down_revision: Union[str, Sequence[str], None] = 'cfc3f6f2935e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'consent_photo_storage')
    op.drop_column('users', 'consent_photo_storage_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('consent_photo_storage_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('consent_photo_storage', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
