"""add overall_score

Revision ID: 62c74ec97e2f
Revises: 616f5d550c0c
Create Date: 2026-07-12 14:59:04.276880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c74ec97e2f'
down_revision: Union[str, Sequence[str], None] = '616f5d550c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('overall_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'overall_score')
    # ### end Alembic commands ###
