"""Add paywall fields to user

Revision ID: 98c7d9e4c865
Revises: befb9c205f40
Create Date: 2026-07-14 13:29:56.123952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c7d9e4c865'
down_revision: Union[str, Sequence[str], None] = 'befb9c205f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_tier', sa.String(), server_default='free', nullable=False))
    op.add_column('users', sa.Column('scans_used', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'scans_used')
    op.drop_column('users', 'subscription_tier')
    # ### end Alembic commands ###
