"""Add consent fields to analysis

Revision ID: cfc3f6f2935e
Revises: 1a555ce05e87
Create Date: 2026-07-07 23:56:42.158168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc3f6f2935e'
down_revision: Union[str, Sequence[str], None] = '1a555ce05e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('consent_photo', sa.Boolean(), nullable=True))
    op.add_column('analyses', sa.Column('consent_photo_given_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'consent_photo_given_at')
    op.drop_column('analyses', 'consent_photo')
    # ### end Alembic commands ###
