"""initial

Revision ID: f6ea3703747f
Revises: 
Create Date: 2026-06-02 23:06:07.577879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ea3703747f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_analysis', sa.Boolean(), nullable=True),
    sa.Column('consent_analysis_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_photo_storage', sa.Boolean(), nullable=True),
    sa.Column('consent_photo_storage_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('skin_type', sa.String(), nullable=True),
    sa.Column('skin_tone', sa.String(), nullable=True),
    sa.Column('result_json', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('top_concerns', sa.dialects.postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('age_range', sa.String(), nullable=True),
    sa.Column('primary_concern', sa.String(), nullable=True),
    sa.Column('region_country', sa.String(), nullable=True),
    sa.Column('region_state', sa.String(), nullable=True),
    sa.Column('photo_object_key', sa.String(), nullable=True),
    sa.Column('ai_provider', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('waitlist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('interest', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_email'), 'waitlist', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waitlist_email'), table_name='waitlist')
    op.drop_table('waitlist')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
